### ISSUE TITLE
delete函数有问题

### ISSUE THREAD

**Issue by db-murphy** [node-webot/webot#31]
看看你的utils.js的remove函数的第二个for in 循环吧  哎

写成这样才对

for(var i in index) {
    obj.splice(index[i], 1);
  }

**Comment by ktmud** [comment]
对不起让您失望了。

**Comment by db-murphy** [comment]
额额额额，你还发邮件啊，严重了，哈哈。^_^!!                             原始邮件                             发件人: Jesse Yang<notifications@github.com>收件人: node-webot/webot<webot@noreply.github.com>抄送: D.B-Murphy<rainbolean@sina.com>发送时间: 2015年4月15日(周三) 18:26主题: Re: [webot] delete函数有问题 (#31)对不起让您失望了。
